project:
  type: book
  output-dir: _site

book:
  title: "Cognitive Neuroscience 2425 - Small Group Sessions"
  author: "Javier Ortiz-Tudela (feat. Carlos González-García)"
  date: "September, 2024"
  chapters:
    - index.qmd
    - part: "Course Information"
      chapters:
        - introduction.qmd
    - part: "Weekly Content"
      chapters:
        - week_0.qmd
        - week_1.qmd
        - week_2.qmd
        - week_3.qmd
        - week_4.qmd
        - week_5.qmd
        - week_6.qmd
        - week_7.qmd
        - week_8.qmd
        - week_9.qmd
        - week_10.qmd
        - week_11.qmd
        - week_12.qmd

format:
  html:
    theme: cosmo
    number-sections: false 
  pdf:
    documentclass: scrreprt

bibliography: references.bib
bibliography-style: apa
