# Introduction to Cognitive Neuroscience and the Podcast Project

Welcome to the small group sessions of the Cognitive Neuroscience course! These sessions are conceived to be a learning experience which combines in-depth study of some key areas of cognitive neuroscience with the practical application of science communication through podcast creation.

## Course Overview

This course is designed as a 13-week journey that will take you through all the necessary steps starting from coming out with a scientific question, finding information about it, critically thinking about this information, and to eventually create a summary of the learned information in audio format. Throughout the semester, you will work in groups of 3-4 students to create a 5-10 minute podcast episode on a specific subtopic within cognitive neuroscience.

## Course Objectives

By the end of this course, you will:

1. Gain in-depth knowledge in a specific area within Cognitive Neuroscience
2. Learn to review, critically analyze and synthesize scientific literature
3. Gain experience in interviewing experts scientists in the field
4. Develop proficiency in sythesizing and communicating scientific information to diverse audiences
5. Acquire basic skills in recording and editing audio content generally and on podcast production more concretely
6. Enhance your teamwork and project management skills

## Course Instructors

- **Rodika Sokoliuk**
  - Email: sokoliuk@ugr.es
  - Office: 303 at CIMCYC

- **Juan Linde Domingo**
  - Email: lindedomingo@ugr.es
  - Office: 308 at CIMCYC

- **Javier Ortiz Tudela**
  - Email: ortiztudela@ugr.es
  - Office: 308 at CIMCYC

Note: While we have office hours, it's usually better if you send us an email in advance so that we can prepare for your questions.

## Getting Started

As we embark on this journey together, keep an open mind, be curious, and *don't be afraid to ask questions*. Cognitive neuroscience is fascinating and complex, and your task is to make it accessible and engaging for the audience.

In the next section, we'll dive into the course roadmap, giving you a clear picture of what to expect in the coming weeks.