# Week 11: Recording and Audio Editing (Part 2) and Final product
As we approach the end, you will continue with recording, editing, re-recording and re-editing as many times as needed. This week you will be working autonomously but you can always seek guidance during of the in-person session or via email. By the end of the week you should submit your podcast.

## Objectives
- Continue recording if any bits are missing still.
- Review and revise the entire podcast episode as a group.
- Make necessary edits to enhance the episode's flow and quality.
- Submit the assignment

## Tasks
1. **Audio Editing:**
   - Begin editing the recorded audio to improve clarity and coherence.
   - Remove any unnecessary parts or background noise.
   - Add background music, sound effects, transitions, etc.

1. **Review and Revise:**
   - Listen to the entire podcast episode as a group.
   - Provide feedback on the flow, coherence, and overall quality.
   - Make necessary edits to enhance the episode.

1. **Submit the final podcast:**
   - We will open a platform in Prado
   - One of your group members must submit a single audio file (.mp3) and a pdf with the references used.

## Next Steps
- In the next two sessions we will listen to the recordings of all the groups. This will be beneficial for your group both as listeners and as creators. Also, you will have the opportunity of voting the podcast that you like most.

This week is crucial for refining your podcast episode. Make sure to address all feedback and focus on producing a high-quality final product.
