# Week 7: Recording Interviews (Part 2) + Script Writing (Part 2)
This is week is a continuation of week 6 for autonomous work, for getting feedback from the course instructors and to deliver the **third milestone**.

## Objectives
- Continue recording interviews.
- Review and adjust the episode outline if necessary.
- Continue writing the script.

## Key Ideas from Previous Sessions
- Importance of high-quality interviews for efficiently acquiring information.
- Structuring a compelling script for the podcast episode.
- If you are including the interviews, ensure they are well integrated.

## Tasks
1. **Recording Interviews:**
   - Continue with the interview recordings.

2. **Review and Adjust Outline:**
   - Revisit the episode outline and make necessary adjustments based on new insights from the interviews.

3. **Script Writing:**
   - Continue drafting the script for your podcast episode.
   - Ensure the script flows logically and incorporates feedback from previous sessions.

4. **Do you need feeback?**
   - Reach out! Use the allocated times for this week's session to come ask for questions.

## Milestone 3
Send us the current draft of your script by the end of this week. This script needs to be as detailed as your podcast format needs it to be. If you are going to a fully-scripted type of podcast, then everything that you will say needs to be written; if you are going to an intermediate type, then include as many information as you will need during the recording; if you are going for total improvisation make sure the have listed at least some talking points so that the conversation does not divert too much.

You will have a task in PRADO for one of your group members to upload the file.

## Next Steps
In the next couple of sessions we will do an introduction to podcast recording tools and techniques and basic audio editing techniques. While this week involves a significant amount of autonomous work, remember to reach out for guidance and feedback as needed. Collaborative efforts and continual refinement are key to creating a successful podcast episode.
