# Week 1: Topic Selection and Research

## Objectives
By the end of this week, students will:

- Have a quick recap of the goal of the course to get new students on board
- Be introduced to potential pitfalls in Cognitive Neuroscience research
- Select their preferred topics
- Be assigned to groups based on their preferences

## Milestones and Delivery Dates
We'll review the project milestones and their expected delivery dates. This will help you plan your work and ensure you stay on track throughout the course.

## A Skeptical Approach to Cognitive Neuroscience Research
In this section, we'll discuss common pitfalls and areas of caution in Cognitive Neuroscience research. This "skeptical watchlist" will help you approach your research with a critical eye and ensure the scientific integrity of your podcast content.

You can find the slides for this section below.

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS1OwH5ZgBDFa9Lh_dBNbF7Giw9otT69rhwGYGfhJwtr8mqX7LjyGRRB8WyynTiBBlVYGstB531GN0T/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Tasks
1. Review the available topics and associated papers.
2. Consider your interests and rate your preferences for the different topics.


## Next Steps
In the coming weeks, you'll dive deeper into your chosen topic, conduct in-depth research, and begin planning your podcast episode. Start thinking about what aspects of your topic you find most intriguing and what questions you'd like to explore further.