name: Update Quarto Book
on:
  push:
    paths:
      - '_teaching_materials/ncc-2425/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Render Quarto Book
      run: |
        cd path/to/quarto/book
        quarto render
    - name: Copy to Jekyll site
      run: |
        mkdir -p teaching/quarto-book
        cp -R _teaching_materials/ncc-2425/_site/* teaching/ncc-2425_book/
    - name: Commit and push if changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Quarto book" || exit 0
        git push