name: Update Quarto Book
on:
  push:
    paths:
      - '_teaching_materials/ncc-2425/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install TinyTeX
      run: quarto install tinytex
    - name: Render Quarto Book
      run: |
        cd _teaching_materials/ncc-2425
        quarto render
    - name: Copy to Jekyll site
      run: |
        mkdir -p teaching/ncc-2425_book
        cp -R _teaching_materials/ncc-2425/_site/* teaching/ncc-2425_book/
    - name: Commit and push if changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Quarto book" || exit 0
        git push
